import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  wrap: {
    width:'100%',
    height:'100%',
    // alignItems:'flex-end',
  },
  beauty:{
    backgroundColor:'#fff',
    marginTop:10,
    marginLeft:10,
  },
  banner:{
    width:'100%',
    height:'100%'
  },
  toplogo:{
    position:'absolute',
    right:0,
    top:0,
    width:44,
    height:44,
    zIndex:1
  },
  detail:{
    position:'absolute',
    bottom:0,
    justifyContent:'flex-end',
    width:'100%',
    height:'100%',
  },
  detailtxt:{
    fontSize:14,
    marginLeft:5,
    color:'#fff',
    fontWeight:'600',
    marginBottom:'2.5%'
  },
  user:{
    flexDirection:'row',
    marginTop:10,
    marginBottom:10
  },
  userlogo:{
    width:40,
    height:40,
    borderRadius:10,
    marginLeft:10,
    marginRight:10
  },
  userinfo:{
    justifyContent:'flex-end',
  },
  username:{
    fontWeight:'500',
    marginBottom:10,
  },
  userdate:{
    fontSize:10,
    color:'#9e9e9e'
  },
  interact:{
    flexDirection:'row',
    paddingLeft:15,
    paddingRight:15,
    marginBottom:15,
    justifyContent:'space-between',
    alignItems:'center',
  },
  goodandlike:{
    flexDirection:'row',
    alignItems:'center',
  },
  like:{
    width:18,
    height:18
  },
  good:{
    width:16,
    height:16,
    marginLeft:15
  },
  num:{
    color:'#979797',
    marginLeft:5
  },
  concern:{
    justifyContent:'center',
    alignItems:'center',
    width:60,
    height:30,
    backgroundColor:'#ff666b',
    borderRadius:5
  },
  concerntxt:{
    fontSize:12,
    color:'#fff',
    fontWeight:'400'
  }
})

