import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  container: {
    width:'100%',
    height:'100%',
    position:'absolute',
    justifyContent:'flex-end',
    alignItems:'center'
  },
  women:{
    position:'absolute',
    width:'100%',
    height:'100%'
  },
  cover:{
    backgroundColor:'rgba(198,193,187,0.2)',
    position:'absolute',
    width:'100%',
    height:'100%'
  },
  left:{
    position:'absolute',
    width:25,
    height:25,
    top:25,
    left:10
  },
  logo:{
    position:'absolute',
    width:130,
    height:30,
    top:'15%'
  },
  form:{
    position:'absolute',
    top:'32%',
    width:'85%',
    height:300
  },
  input:{
    width:'100%',
    flexDirection:'row',
    borderBottomWidth:1,
    borderBottomColor:'#fff',
    padding:10,
    position:'absolute',
    alignItems:'center'
  },
  inputlogo:{
    width:16,
    height:16
  },
  inputtxt:{
    height:22,
    width:'85%',
    marginLeft:10,
    color:'#fff',
  },
  clear:{
    position:'absolute',
    width:14,
    height:14,
    right:10,
  },
  passwordshow:{
    position:'absolute',
    width:14,
    height:14,
    right:10,
  },
  forgot:{
    fontSize:11,
    color:'#fff',
    position:'absolute',
    right:0,
    top:120
  },
  signwrap:{
    alignItems:'center'
  },
  signbtn:{
    backgroundColor:'#ff666b',
    width:300,
    height:50,
    borderRadius:25,
    shadowColor:'#ff666b',
    shadowOffset:{ width: 0, height: 7 },
    shadowOpacity:0.5,
    shadowRadius:3,
    justifyContent:'center',
    alignItems:'center'
  },
  signtxt:{
    fontSize:16,
    fontWeight:'500',
    color:'#fff',
  },
  gosign:{
    color:'#fff',
    fontSize:12,
    marginTop:35
  },
  other:{
    fontSize:10,
    color:'#fff',
    marginTop:20
  },
  logowrap:{
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:10,
    marginBottom:5,
    width:200
  },
  logologo:{
    width:25,
    height:25
  }
})

